### PR TITLE
Removed non-decorator fuss from README.md

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #12.

I filed that issue over a month ago, and it's a simple fix. Seems weird that it wasn't fixed by now.

### CODE REVIEW

**Comment by smikula** [comment]
Unfortunately this awkward syntax is still necessary -- Typescript punted on this work and it's now listed under "Future" in their [roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap).  (The item it depends on is "Decorators for function expressions/arrow functions").

But you're right that the reference to 2.0 is out of date; probably we should update it to "a future version of Typescript".

**Comment by kenotron** [comment]
I am not sure how this change is supposed to fix #12. Also, I don't think we should document a feature that doesn't exist in TS yet.

**Comment by kenotron** [comment]
I don't think we should change up the examples for now since that syntax isn't valid right now.

**Comment by JoshuaKGoldberg** [comment]
Ah ok. The issue now is that your readme mentions TS 2.0 specifically. I'll file a separate PR.

**Pull request closed without merging**
